project_id = "lvvvjywrmpcqrpvuptdi"

[db]
shadow_port = 54332

[functions.sync-campaign-to-edusite]
verify_jwt = false

[functions.sync-registrations-from-edusite]
verify_jwt = false

[functions.notifications-dispatcher]
verify_jwt = false
