// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/ai-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ai-config">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ai-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/ai-usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ai-usage">> = Specific
  const handler = {} as typeof import("../../src/app/admin/ai-usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/caps-mapping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/caps-mapping">> = Specific
  const handler = {} as typeof import("../../src/app/admin/caps-mapping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/deletion-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/deletion-requests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/deletion-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/promotions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/promotions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/promotions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/registrations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/registrations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/registrations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/registrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/registrations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/registrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/aftercare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aftercare">> = Specific
  const handler = {} as typeof import("../../src/app/aftercare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/aftercare/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aftercare/register">> = Specific
  const handler = {} as typeof import("../../src/app/aftercare/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apply/[job_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/[job_id]">> = Specific
  const handler = {} as typeof import("../../src/app/apply/[job_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply">> = Specific
  const handler = {} as typeof import("../../src/app/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth-callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth-callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth-callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/centers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/centers">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/centers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/courses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/courses/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/courses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/courses">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/instructors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/instructors">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/instructors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-tertiary/students">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/aftercare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/aftercare">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/aftercare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/organizations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor/courses">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/grading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor/grading">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/grading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/instructor/students">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/activities">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/aftercare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/aftercare">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/aftercare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/ai-help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/ai-help">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/ai-help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/birthday-chart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/birthday-chart">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/birthday-chart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/birthday-memories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/birthday-memories">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/birthday-memories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/calls">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/children/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/children">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/children/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/claim-child/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/claim-child">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/claim-child/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/class-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/class-code">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/class-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/daily-program/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/daily-program">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/daily-program/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/dash-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/dash-chat">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/dash-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/documents">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/ebooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/ebooks">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/ebooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/exam-prep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/exam-prep">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/exam-prep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/generate-exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/generate-exam">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/generate-exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/generate-resource/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/generate-resource">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/generate-resource/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/homework-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/homework-history">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/homework-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/homework/[assignmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/homework/[assignmentId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/homework/[assignmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/homework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/homework">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/homework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/learning-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/learning-hub">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/learning-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/lessons/[assignmentId]/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/lessons/[assignmentId]/play">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/lessons/[assignmentId]/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/lessons/[assignmentId]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/lessons/[assignmentId]/view">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/lessons/[assignmentId]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/lessons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/lessons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/menu">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/my-exams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/my-exams">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/my-exams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/name-practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/name-practice">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/name-practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/payments/flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/payments/flow">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/payments/flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/payments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/payments/pop-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/payments/pop-history">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/payments/pop-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/payments/pop-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/payments/pop-upload">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/payments/pop-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/picture-of-progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/picture-of-progress">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/picture-of-progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/progress">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/register-child/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/register-child">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/register-child/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/robotics/intro-robotics-r-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/robotics/intro-robotics-r-3">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/robotics/intro-robotics-r-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/robotics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/robotics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/robotics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/robotics/shapes-patterns-r-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/robotics/shapes-patterns-r-2">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/robotics/shapes-patterns-r-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/settings/ringtones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/settings/ringtones">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/settings/ringtones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/standalone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/standalone">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/standalone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/stationery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/stationery">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/stationery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/upgrade/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/upgrade/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/upgrade/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/upgrade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/upgrade">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/upgrade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/upgrade/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/upgrade/success">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/upgrade/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/weekly-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parent/weekly-report">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/weekly-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/activities">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/ai-year-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/ai-year-planner">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/ai-year-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/budget-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/budget-overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/budget-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/communications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/compliance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/curriculum-themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/curriculum-themes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/curriculum-themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/dash-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/dash-chat">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/dash-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/excursions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/excursions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/excursions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/financials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/financials">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/financials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/join-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/join-requests">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/join-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/learner-activity-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/learner-activity-control">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/learner-activity-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/lesson-approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/lesson-approvals">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/lesson-approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/lesson-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/lesson-templates">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/lesson-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/menu">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/registrations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/registrations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/registrations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/registrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/registrations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/registrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/reports/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/reports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/reports/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/reports/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/reports/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/reports/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/settings/fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/settings/fees">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/settings/fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/settings/learner-lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/settings/learner-lifecycle">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/settings/learner-lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/settings/report-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/settings/report-card">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/settings/report-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/settings/school-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/settings/school-profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/settings/school-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/staff-leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/staff-leave">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/staff-leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/stationery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/stationery">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/stationery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/stem-programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/stem-programs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/stem-programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/students/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/students/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/students/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/students/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/students/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/students/enroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/students/enroll">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/students/enroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/students">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/teacher-payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/teacher-payroll">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/teacher-payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/teachers/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/teachers/invite">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/teachers/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/timetable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/timetable">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/timetable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/uniforms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/uniforms">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/uniforms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/waitlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/waitlist">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/waitlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/weekly-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/weekly-plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/weekly-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/principal/year-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/principal/year-planner">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/principal/year-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/activities">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/ai-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/ai-assistant">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/ai-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/ai-grader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/ai-grader">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/ai-grader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/approval-pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/approval-pending">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/approval-pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/birthdays">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/calls">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/class-codes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/class-codes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/class-codes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/classes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/classes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/classes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/classes/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/classes/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/classes/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/classes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/dash-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/dash-chat">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/dash-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/family-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/family-review">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/family-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/groups">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/homework/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/homework/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/homework/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/homework/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/homework/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/homework/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/homework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/homework">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/homework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/interactive-activities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/interactive-activities">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/interactive-activities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/lessons/[lessonId]/assign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/lessons/[lessonId]/assign">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/lessons/[lessonId]/assign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/lessons/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/lessons/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/lessons/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/lessons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/lessons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/live-lesson/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/live-lesson">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/live-lesson/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/menu">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/reports/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/reports/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/reports/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/reputation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/reputation">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/reputation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/settings/ringtones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/settings/ringtones">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/settings/ringtones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/students/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/students/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/test-call/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/test-call">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/test-call/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/tutor-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/tutor-analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/tutor-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/weekly-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/weekly-plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/weekly-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-deletion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-deletion">> = Specific
  const handler = {} as typeof import("../../src/app/data-deletion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/display/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/display">> = Specific
  const handler = {} as typeof import("../../src/app/display/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ecd/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecd/play">> = Specific
  const handler = {} as typeof import("../../src/app/ecd/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/exam-prep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exam-prep">> = Specific
  const handler = {} as typeof import("../../src/app/exam-prep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/executive">> = Specific
  const handler = {} as typeof import("../../src/app/invite/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/member">> = Specific
  const handler = {} as typeof import("../../src/app/invite/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/invite/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jobs/[job_id]/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[job_id]/apply">> = Specific
  const handler = {} as typeof import("../../src/app/jobs/[job_id]/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/popia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/popia">> = Specific
  const handler = {} as typeof import("../../src/app/popia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registration/pop-upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration/pop-upload">> = Specific
  const handler = {} as typeof import("../../src/app/registration/pop-upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/organization">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/parent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/parent">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/parent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/pending-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/pending-approval">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/pending-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/principal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/principal">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/principal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/teacher/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/teacher/success">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/teacher/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher-signup">> = Specific
  const handler = {} as typeof import("../../src/app/teacher-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-payfast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-payfast">> = Specific
  const handler = {} as typeof import("../../src/app/test-payfast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-proxy">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/sign-up-principal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-up-principal">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/sign-up-principal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/custom-plan-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-plan-quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/custom-plan-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily/rooms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily/rooms">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily/rooms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily/token">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/display/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/display/data">> = Specific
  const handler = {} as typeof import("../../src/app/api/display/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/display/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/display/link">> = Specific
  const handler = {} as typeof import("../../src/app/api/display/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/display/pair/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/display/pair/claim">> = Specific
  const handler = {} as typeof import("../../src/app/api/display/pair/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/display/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/display/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/display/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/display/routine-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/display/routine-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/display/routine-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/early-access-notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/early-access-notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/early-access-notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invites/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/invites/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/deployment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/deployment">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/deployment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payfast/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payfast/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/payfast/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/principal/teachers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/principal/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/api/principal/teachers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registrations/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registrations/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/registrations/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registrations/pop-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registrations/pop-upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/registrations/pop-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registrations/verify-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registrations/verify-payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/registrations/verify-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/students/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/students/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/signout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/signout">> = Specific
  const handler = {} as typeof import("../../src/app/auth/signout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apply/[job_id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/apply/[job_id]">> = Specific
  const handler = {} as typeof import("../../src/app/apply/[job_id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-tertiary/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin-tertiary">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-tertiary/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/instructor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/instructor">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/instructor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parent/standalone/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/parent/standalone">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parent/standalone/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/display/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/display">> = Specific
  const handler = {} as typeof import("../../src/app/display/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/teacher/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/invite/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/invite/teacher/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-up/teacher/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-up/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/sign-up/teacher/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
