var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/parent/register-child/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__17db77d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_ef192466._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/253c0__next-internal_server_app_dashboard_parent_register-child_page_actions_1c8f6f34.js")
R.m(846879)
module.exports=R.m(846879).exports
