var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/caps-mapping/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__28805c82._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_de423821._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/web_src_app_admin_layout_tsx_37c160a4._.js")
R.c("server/chunks/ssr/web__next-internal_server_app_admin_caps-mapping_page_actions_42bc9ed7.js")
R.m(686464)
module.exports=R.m(686464).exports
