var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/sign-up/teacher/success/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc11de57._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_2ad8963b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/web_src_app_sign-up_teacher_layout_tsx_1e31391b._.js")
R.c("server/chunks/ssr/web__next-internal_server_app_sign-up_teacher_success_page_actions_c88f9c27.js")
R.m(251574)
module.exports=R.m(251574).exports
