var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin-tertiary/centers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d524e80c._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_1f1e6852._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/web_src_app_dashboard_admin-tertiary_layout_tsx_09fa16fe._.js")
R.c("server/chunks/ssr/c79f2_next-internal_server_app_dashboard_admin-tertiary_centers_page_actions_80f5fcf4.js")
R.m(251672)
module.exports=R.m(251672).exports
