var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/aftercare/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1f2befb._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_63449e9a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/web__next-internal_server_app_dashboard_admin_aftercare_page_actions_5e5bddee.js")
R.m(583112)
module.exports=R.m(583112).exports
