var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/parent/attendance/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__63e6e60a._.js")
R.c("server/chunks/ssr/2374f_next_dist_62edd160._.js")
R.c("server/chunks/ssr/web_a0c3822f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__793f0de4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__227b2dff._.js")
R.c("server/chunks/ssr/2374f_next_dist_7b2c45d8._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_global-error_81159d60.js")
R.c("server/chunks/ssr/[root-of-the-server]__99b295f3._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_9c5d1a14._.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_forbidden_8eae0c85.js")
R.c("server/chunks/ssr/2374f_next_dist_client_components_builtin_unauthorized_7d34a31c.js")
R.c("server/chunks/ssr/web__next-internal_server_app_dashboard_parent_attendance_page_actions_f70a7446.js")
R.m(992065)
module.exports=R.m(992065).exports
